[package]
name = "raddyspring"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "*"
nalgebra = "*"
faer = "*"
faer-sparse = "*"
# replace with the newest version
raddy-ad = { path = "../raddy" }
